FDBCORE-986: add autofdo and its dependency to image
FoundationDB/fdb-build-support pull request #17
Opened 2022-01-21 21:48 UTC by sfc-gh-zyang

Add autofdo to image, it'll be used to convert perf profile to llvm profile.

2022-02-17 21:05 UTC, ammolitor requested changes

2022-02-17 21:05 UTC, ammolitor commented on docker/centos7/Dockerfile
> +        # Enable RTTI for autofdo
remove the comment, or add it to the comment block at the beginning of the LLVM build/install

2022-02-17 21:05 UTC, ammolitor commented on docker/centos7/Dockerfile
> +        # Enable RTTI for autofdo
remove the comment, or add it to the comment block at the beginning of the LLVM build/install

2022-03-01 07:19 UTC, sfc-gh-zyang commented
Thanks for your comment, this pr is not necessary any more since https://github.com/apple/foundationdb/pull/6396 is merged. These 2 PRs use 2 different method to collect profile, sampling and instrumentation, finally I choose instrumentation.

2022-03-01 07:19 UTC, closed without merging