Add rust compiler to FDB dev environment
FoundationDB/fdb-build-support pull request #20
Opened 2022-03-01 19:00 UTC by vishesh

Installs Rust compiler in Okteto image, for `fdb-backup` project.

2022-03-01 19:02 UTC, vishesh commented
Trying to build Docker image to test and see if it works as expected. Currently timing before trying import centos repo keys:

```
#6 360.6   - Curl error (28): Timeout was reached for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Connection timed out after 30006 milliseconds]
#6 360.6   - Curl error (28): Timeout was reached for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Connection timed out after 30002 milliseconds]
#6 360.6   - Curl error (28): Timeout was reached for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Connection timed out after 30003 milliseconds]
#6 360.6   - Curl error (28): Timeout was reached for http://mirrorlist.centos.org/?release=8&arch=x86_64&repo=AppStream&infra=container [Connection timed out after 30001 milliseconds]
```

2022-03-01 21:35 UTC, ammolitor requested changes

2022-03-01 21:35 UTC, ammolitor commented on docker/centos8/Dockerfile
> +    source $HOME/.cargo/env;
does this need to be sourced in the user shell? If so, it should move to the `.bashrc` section in the `devel` image.

2022-03-01 21:35 UTC, ammolitor commented on docker/centos8/Dockerfile
> +# Download Rust binaries
Please take a look at how the `golang` install is done above. The sticky bit is the sha256sum of the binary file that is being downloaded. We use that as a protection against downloading an incorrect/corrupt binary. The team at SF is pretty particular about this pattern, it is driven by their infosec policies.

2022-03-02 21:16 UTC, ammolitor approved these changes

2022-03-02 21:17 UTC, merged